### ISSUE TITLE
Sample Model Error "Not Valid"

### ISSUE THREAD

**Issue by MatanBaruchTempo** [tabulartools/dax-optimizer#31] opened 2024-07-26 04:02 UTC
### Describe the problem

Sample Model not working

### Power BI

Power BI Desktop version July 2024

### Screenshots

![image](https://github.com/user-attachments/assets/163e3a52-5eab-46f7-b8f9-f2bfbd413616)

### Anything else ?

Trace id: 102c11cc-2c24-977b-8b19-618280bf4044

**Comment by albertospelta** [comment] 2024-07-29 10:05
We are closing this issue as the root cause was the same as discussed and resolved in issue #30 (as per [this comment](https://github.com/tabulartools/dax-optimizer/issues/30#issuecomment-2255243495))

**Closed as completed by albertospelta** 2024-07-29 10:05 UTC
