### ISSUE TITLE
Analyze could not be completed ...

### ISSUE THREAD

**Issue by aminegara** [tabulartools/dax-optimizer#47] opened 2024-12-16 15:18 UTC
### Describe the problem

I received the error when doing the first analyze

### Power BI

power bi desktop 1.137.751.0 (October 2024)

### Steps to reproduce the behavior

I received the error when doing the first analyze

### Anything else ?

Trace id: db516155-cfc9-04fa-4296-35ff365d94af

**Comment by albertospelta** [comment] 2024-12-16 15:42
@aminegara Thank you for reporting this issue. We’ve identified the error and are investigating the cause. We’ll keep you updated.

**Comment by albertospelta** [comment] 2024-12-16 17:30
@aminegara the fix for has been deployed in production and you can now [re-run the analysis](https://docs.daxoptimizer.com/glossary/re-run) on the model.
Please, let us know if everything is working as expected.

**Comment by albertospelta** [comment] 2024-12-20 11:14
I'm closing this issue as, from what we can see, the error has been resolved and the analysis successfully completed.
If you need further help, feel free to comment here, and we’ll reopen it. Thanks!

**Closed as completed by albertospelta** 2024-12-20 11:14 UTC
Labels: bug
