### ISSUE TITLE
Error 400: Vpax cannot be optimized (DO100011)

### ISSUE THREAD

**Issue by MeieLead** [tabulartools/dax-optimizer#12] opened 2023-10-02 13:49 UTC
### Describe the problem

Error 400: Vpax cannot be optimized (DO100011)
The Vpax cannot be optimized [Incompatible license].

### Power BI

Power BI desktop August 2023

### Anything else ?

Trace id: 4bb3d6e9-9ff3-4c42-b708-0707fc0102bc

**Comment by albertospelta** [comment] 2023-10-02 14:39
Hi @MeieLead, you are getting this error probably because the tool (Bravo/DaxStudio/TabularEditor) you used to extract the Vpax file is out of date. Can you try updating the tool to the latest version and then try again with DaxOptimizer using a new extracted Vpax file?

**Comment by MeieLead** [comment] 2023-10-02 14:47
Hi Alberto,

Thank you. I already updated Dax studio and now it works.

Meie Kooistra
Power BI Specialist

[signature_1450862835]

Luitenant Generaal van Heutszlaan 8
3743 JN Baarn
T: +31(0)35 – 5430234
M:+31 (0)6 – 51703546
W: www.leadhealthcare.nl<http://www.leadhealthcare.nl/>


Van: Alberto Spelta ***@***.***>
Verzonden: maandag 2 oktober 2023 16:40
Aan: tabulartools/dax-optimizer ***@***.***>
CC: Meie Kooistra ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tabulartools/dax-optimizer] Error 400: Vpax cannot be optimized (DO100011) (Issue #12)

U ontvangt niet vaak e-mail van ***@***.******@***.***>. Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Hi @MeieLead<https://github.com/MeieLead>, you are getting this error probably because the tool (Bravo/DaxStudio/TabularEditor) you used to extract the Vpax file is out of date. Can you try updating the tool to the latest version and then try again with DaxOptimizer using a new extracted Vpax file?

**Comment by albertospelta** [comment] 2023-10-02 14:55
Duplicate of #5

**Closed by albertospelta** 2023-10-02 14:55 UTC
Labels: duplicate
