### ISSUE TITLE
Getting not valid error after importing ,vpax file

### ISSUE THREAD

**Issue by ricky7uio** [tabulartools/dax-optimizer#37] opened 2024-11-04 08:21 UTC
### Describe the problem

Error 500: Failed to fetch.
GET /v1/vpax/251671593361-0822a08a-781a-4cef-a485-d8e47cd94fad/251671592489-d11eb2ce-1a78-46e0-899f-78324acb9e2f/251671592485-ab033b64-bcd0-4923-958d-0842306f8a59/file

### Power BI

TE 3.18 and online dax optimizer app

### Steps to reproduce the behavior

1 upload the vpax file
2 got the error 
![image](https://github.com/user-attachments/assets/e38bb541-d9b5-4240-96bd-4a849f85703e)

### Additional context

do you need the .vpax file? 

### Anything else ?

Trace id: 31f94fced4d59cb5eb0880d441104d3b

**Comment by albertospelta** [comment] 2024-11-04 11:15
Thank you @ricky7uio for reporting the issue. The error you’re encountering is likely due to the VPAX file becoming corrupted during the upload. Could you please try the steps indicated here https://github.com/tabulartools/dax-optimizer/issues/34#issuecomment-2454402540 and let us know if the extraction of the VPAX files is successful (step 2) and if you are able to analyze your model? Thank you!

**Comment by ricky7uio** [comment] 2024-11-04 11:25
Hi Alberto, 
I retried the process with the same result. 
I am able to successfully save the vpax file. I applied the same settings as adviced in the guide. 

However, when importing the file I see this:
![image](https://github.com/user-attachments/assets/38a52072-da62-40e0-96d0-283287dec918)

thank you!

**Comment by albertospelta** [comment] 2024-11-04 12:55
@ricky7uio From what I can see from the telemetry, it appears that your VPAX was uploaded successfully and is fully compatible for analysis. I suspect that the `Failed to fetch` error may be related to some security filter/check that allow the HTTP request for uploading the file but block the download.

Could you check if you receive the same `Failed to fetch` error when you select one of the sample models?
You can refer to this issue where a similar problem was reported: https://github.com/tabulartools/dax-optimizer/issues/31.

If this error occurs with the sample models as well, then the cause could likely be similar to what is described here: https://github.com/tabulartools/dax-optimizer/issues/30#issuecomment-2252341677.

**Comment by ricky7uio** [comment] 2024-11-04 13:11
Hello Alberto,

I had the same issue trying the sample models. So I followed the instructions, and I just sent the log on an email to you. 

![image](https://github.com/user-attachments/assets/2cf97d47-883e-4deb-96f5-35022c071fcd)

Pls let me know if I can help further. Maybe is my company firewall… hope not.

Thanks.

**Comment by albertospelta** [comment] 2024-11-04 17:13
@ricky7uio, I'm closing the issue since, as discussed offline, the download is being blocked by a corporate firewall/gateway that is preventing the HTTP request to download the file. If you need any further information, feel free to write here, and we can reopen the issue if needed.

**Closed as completed by albertospelta** 2024-11-04 17:13 UTC
