### ISSUE TITLE
License Activation 

### ISSUE THREAD

**Issue by arnaudbs** [tabulartools/dax-optimizer#29] opened 2024-07-23 20:38 UTC
### Describe the problem

Tried uploading my activation code and was not able to apply my purchased license to any model.  Now my activation code does not work.
![image](https://github.com/user-attachments/assets/e3eb5c2b-9670-4f87-b41e-4397ea57133d)
![image](https://github.com/user-attachments/assets/9e09e629-c13c-4d8d-b017-68b9cc186cc6)

### Power BI

Didn't even get this far

### Steps to reproduce the behavior

1. Try activation code
2. Code doesnt work
3. gg

**Comment by albertospelta** [comment] 2024-07-23 21:13
Hi @arnaudbs, we are currently investigating the problem and will update you as soon as we have identified the cause.

**Comment by albertospelta** [comment] 2024-07-23 21:32
@arnaudbs we found that your license is activated and assigned to a group previously created within your organization in DaxOptimizer. You should be able to use the license after switching to the group using the icon under your profile icon in the top right corner of the screen, as described [here](https://docs.daxoptimizer.com/how-to-guides/managing-groups#how-to-switch-to-a-group).

Please let us know if this resolves your issue.

**Comment by arnaudbs** [comment] 2024-07-24 14:05
Excellent, that worked! Thank you! @albertospelta

**Closed as completed** 2024-07-24 14:05 UTC
