### ISSUE TITLE
Number of Columns discrepancy

### ISSUE THREAD

**Issue by mark-endicott** [tabulartools/dax-optimizer#14] opened 2023-10-09 15:17 UTC
### Describe the problem

Before I run the analysis, there is a discrepancy in the number of Columns shown in the DAX Studio (482) and DAX Optimizer (401). 

![image](https://github.com/tabulartools/dax-optimizer/assets/95371077/6d4aa9d4-60d8-4420-8dfe-648a164fddd1)

and 

![image](https://github.com/tabulartools/dax-optimizer/assets/95371077/045efd97-b23f-4627-8b7c-7a9ef3c88578)

I am showing the results of the same VPAX file in both screenshots, but have obscured the file name & model name for data protection. 

Happy to provide the VPAX file securely. 

### Power BI

Power BI Service VPAX file

**Comment by albertospelta** [comment] 2023-10-09 16:51
> Happy to provide the VPAX file securely.

Hi @mark-endicott, you can send it to [support@tabulartools.com](mailto:support@tabulartools.com)

**Comment by albertospelta** [comment] 2023-10-09 20:14
@mark-endicott thank you for providing us with the VPAX file. 

The discrepancy between the two values is due to a different approach used in counting/displaying the number of columns. Specifically, the count shown by DaxStudio includes all columns of type `RowNumber`, while DaxOptimizer does not. The `RowNumber` columns are internal system columns automatically added by the SSAS server to each table, one per table, which identify the physical location of a row in the table and are not accessible in DAX. 

In a future update we may consider changing this behavior to display a consistent value between DaxOptimizer and DaxStudio but, I can confirm that this difference has no impact on the result of the DaxOptimizer analysis.

**Comment by mark-endicott** [comment] 2023-10-10 08:37
Thank you for the explanation, Alberto that makes perfect sense to me. I thought it would be something trivial like this and was not concerned.

I was flagging in case there was something for you to consider when DAX Optimizer is released to the masses.

Thanks,

Mark Endicott (He/Him)
Lead Analyst | Triangle Information Management
T / 07880 437267    E / ***@***.******@***.***>   W / www.triangle.im<http://www.triangle.im/>
Book a meeting with me<https://calendly.com/mark-endicott>
[Assets/Triangle.jpg]<https://triangle.im/>[Assets/LI.jpg]<http://www.linkedin.com/company/3360115>[Assets/TW.jpg]<https://twitter.com/Triangleinfor>[Assets/YT.jpg]<https://www.youtube.com/user/TriangleBPM>

**Comment by albertospelta** [comment] 2023-10-11 06:57
I am closing this issue as the change will be released in the next version of DaxStudio.

**Closed by albertospelta** 2023-10-11 06:57 UTC
Labels: enhancement
