### ISSUE TITLE
Error preventing analysis -- Vpax cannot be optimized

### ISSUE THREAD

**Issue by rmss-tech** [tabulartools/dax-optimizer#20] opened 2023-12-19 01:43 UTC
### Describe the problem

Error DO300000: Not Found
The requested resource is not found.
POST /v1/job/251707043214-f18d4de0-5b93-4eb8-bc83-5a5cc3edd55b/251703245071-84b49bd9-9fbd-4eb0-9d96-44167124e9b4/251699351574-dfe11d8c-b36e-40e6-8f27-0ef0d32eea4e

### Power BI

October 2023 v2.122.746.0 64-bit

### Steps to reproduce the behavior

1) Uploaded exported .vpax file from the latest version of DAX Studio v3.0.11 (2023-11-21)
2) Error visible when tried to analyze the vpax file with the first of 20 daily licenses

### Screenshots

![image](https://github.com/tabulartools/dax-optimizer/assets/73752209/bc7d5c2f-0acf-4cf0-b557-b9e028000e52)

### Anything else ?

Trace id: 8198d43622c206ae413a2a2263a536d1

**Comment by marcosqlbi** [comment] 2023-12-19 08:15
We will investigate this problem very soon - just a question about the model version: I see this is a "v2" of the model; did you successfully analyze a previous version of the same model, or did you have the same error in the previous version?
Thanks!

**Comment by albertospelta** [comment] 2023-12-19 09:27
Hi @rmss-tech, based on our application telemetry, it seems that two different versions of the VPAX file 'Merchandise Performance20231215.vpax' have been uploaded. The initial file was deleted after upload, and subsequently, a second file was uploaded. Both files were marked as `V2` in DaxOptimizer.
The "resource is not found" error occurred because the first file was uploaded but later deleted. You should be able to resolve this issue by refreshing the page or clicking the refresh button in the panel. 
Let us know if this resolves the problem. Thanks!

![image](https://github.com/tabulartools/dax-optimizer/assets/1957788/0e9c2042-c0e0-4bc6-85e8-f4c633265f28)

As a side question to better understand the issue, could you please clarify whether you uploaded and deleted the files by using DaxOptimizer in two different browser instances, or if you performed these actions sequentially within the same browser instance?

**Comment by rmss-tech** [comment] 2023-12-19 16:42
I tried refreshing the Workspace and re-tried analyzing the previously loaded VPAX file and I still get the same error.

Yesterday, I did try and reproduced the issue from 2 different PCs/browsers.  Unfortunately, I do not remember the order of my multiple attempts.  I had deleted the 1st file after receiving the same error.  I then re exported the file from DAX Studio and got an error.

This is the error I am seeing now (and believe that I got this yesterday as well)
Vpax cannot be optimized
The Pax cannot be optimized (Incompatible license)

I checked my DAX Optimizer license and confirmed that it is valid thru 12/24/2023.

Please advise,

Rob

**Comment by rmss-tech** [comment] 2023-12-19 16:54
The v2 is used to distinguish which license I am using.

I had a DAX Optimizer license that expired (v1).  I then bought another month of license and it limited my use of the previous license models.  So, I created new models (prepended the name with v2 to identify with the 2nd license).  The v2 made it clear to me which models I have full rights to.


Rob

**Comment by marcosqlbi** [comment] 2023-12-19 17:47
Hi Rob, thanks for the info, I try to recap what we have found so far:

- The error "the requested resource is not found" was caused by concurrency in operations over the same model - it should be a rare case and we planned a fix for that, but the workaround is the one described by @albertospelta (hit the Refresh icon).
- The error about the incompatible license is caused by the license you have: with a Desktop license, you can use VPAX files obtained from Power BI Desktop, but not from Power BI Service. 

The simplest workaround is to obtain the VPAX file from Power BI Desktop, so you can continue to use your license without an upgrade to the Service level.
If you obtained the VPAX file from Power BI Desktop and you get the license error, then we have to further investigate and will require more details.

Please, let us know if this clarifies all the doubts or not.
Thanks!

**Comment by rmss-tech** [comment] 2023-12-19 23:44
Thanks - This explanation makes sense and allowed me to successfully use the tool again.

Rob

**Comment by marcosqlbi** [comment] 2023-12-20 07:40
Great - thank you for closing the loop!

**Closed as completed by marcosqlbi** 2023-12-20 07:40 UTC
