### ISSUE TITLE
Can't delete model from previous license that expired (now using new license with same login)

### ISSUE THREAD

**Issue by rmss-tech** [tabulartools/dax-optimizer#17] opened 2023-10-25 14:24 UTC
### Describe the problem

Error DO100003: Contract expired
The contract is expired.
DELETE /v1/model/251707042395-84561f5f-a08c-4ac7-a403-6e3a17588ec6/251707040946-5a983e78-e99b-4720-8857-a0c3409dcfb8

### Power BI

September 2023 v2.121.644.0 64-bit

### Steps to reproduce the behavior

1. Right click on model
2. Select Delete
3. Type model name
4. Received error
Error DO100003: Contract expired
The contract is expired.
DELETE /v1/model/251707042395-84561f5f-a08c-4ac7-a403-6e3a17588ec6/251707040946-5a983e78-e99b-4720-8857-a0c3409dcfb8
Trace id: ad67e772d9a8d8283f1346e954811183
DAX Optimizer v0.1.80

### Anything else ?

Trace id: ad67e772d9a8d8283f1346e954811183

**Comment by albertospelta** [comment] 2023-10-26 10:43
Hi @rmss-tech, deleting a model when the license has expired is not yet supported, but will be implemented in a future update.
I will update this thread once the feature is available.

**Comment by albertospelta** [comment] 2024-02-20 12:34
Closing as duplicate of #21 
See https://github.com/tabulartools/dax-optimizer/issues/21#issuecomment-1954118853

**Closed as completed by albertospelta** 2024-02-20 12:34 UTC
Labels: duplicate
