### ISSUE TITLE
Imcompatible Report

### ISSUE THREAD

**Issue by RHNumbers-dev** [tabulartools/dax-optimizer#11] opened 2023-10-02 04:02 UTC
### Describe the problem

Error 400: Vpax cannot be optimized (DO100011)
The Vpax cannot be optimized [Incompatible license].

### Power BI

Power BI Desktop Version September 2023

### Steps to reproduce the behavior

1. Download vpax by bravo
2. Upload to dax optimizer
3. Analyze it
4. Error
![image](https://github.com/tabulartools/dax-optimizer/assets/117867238/dca20457-5fd6-427b-86a6-afa7972b163c)

### Anything else ?

Trace id: 502525a4-b5c0-d01e-d8f3-293d565dc9a2

**Comment by marcosqlbi** [comment] 2023-10-02 06:31
What is the version of Bravo that you used? If you are not using the latest version, can you try to extract the VPAX file by using the latest version of Bravo?

Thanks!

**Comment by albertospelta** [comment] 2023-10-02 07:36
Duplicate of #5

**Comment by albertospelta** [comment] 2023-10-02 07:52
Hi @RHNumbers-dev, our internal log shows that the issue has been resolved and the analysis was correctly executed.
I am closing this issue but feel free to reopen in case of further issues/questions. Thanks!

**Closed by albertospelta** 2023-10-02 07:52 UTC
