### ISSUE TITLE
VPAX upload failed - File contains corrupted data

### ISSUE THREAD

**Issue by iggyvic** [tabulartools/dax-optimizer#33] opened 2024-11-01 09:54 UTC
### Edit
I was able to export the vpax file and upload it manually through the web interface thoug: 
<img width="686" alt="image" src="https://github.com/user-attachments/assets/b833da23-ad9c-49bf-8503-71925a034402">

### Original issue
Was going to try out the runs included in my TE3 subscription today but my vpax file seems to be corrupted. I followed the steps outlined [here](https://blog.tabulareditor.com/2024/10/31/free-dax-optimizer-access-in-tabular-editor-3/). When uploading though TE3 I got a DirectQuery popup as my model contains one DQ table (rest is import) but was able to proceed. 
<img width="767" alt="Screenshot 2024-11-01 at 10 49 56" src="https://github.com/user-attachments/assets/1515daa8-3ad6-482c-97b3-5e071e0de1ca">
At first it uploaded and said the file contained corrupted data.
<img width="486" alt="Screenshot 2024-11-01 at 10 51 19" src="https://github.com/user-attachments/assets/3d09b222-2643-4e18-93bc-6bdd4f5e6174">
I tried deleting the model but since we can only have one per each 30 day period i deleted the version and tried uploading it again but this time it said the file was corrupted before even uploading it.
<img width="493" alt="image" src="https://github.com/user-attachments/assets/86019120-54c5-4557-b32c-26a0b2f9b7a9">

### Power BI

Tabular Editor 3.18.0.5749, Microsoft Premium P1

### Anything else ?

Trace id: 079a20ae-79b7-c0a1-ac20-6b5c31d0e005

**Comment by marcosqlbi** [comment] 2024-11-01 09:58
Please, can you check whether the "Read statistics from data" setting is enabled in VertiPaq Analyzer settings?

![image](https://github.com/user-attachments/assets/b0dfa377-f9a6-489d-aae2-dc402485419f)

**Comment by iggyvic** [comment] 2024-11-01 10:04
It was not enabled. I don't remember ever diasabling it so I would think this is the default value?
<img width="764" alt="image" src="https://github.com/user-attachments/assets/da81ff9e-9180-4c0d-9730-81532595b785">

**Comment by marcosqlbi** [comment] 2024-11-01 10:08
We're investigating with Tabular Editor - in the meantime, can you try to enable it and repeat the upload from within Tabular Editor?

**Comment by iggyvic** [comment] 2024-11-01 11:02
Sure! Enabling the setting and uploading again resulted in the same error, unfortunately. Uploading manually still works.

<img width="763" alt="image" src="https://github.com/user-attachments/assets/d9026cf0-e1cf-45cb-95a1-25832137ae07">

<img width="683" alt="image" src="https://github.com/user-attachments/assets/5b1cabb3-3a31-4d98-91bb-d91b5f9434fa">

<img width="500" alt="image" src="https://github.com/user-attachments/assets/4a98598f-83e0-41fa-b9ea-eff65d34653e">

**Comment by marcosqlbi** [comment] 2024-11-01 11:05
Thank you for the update. We're investigating on our side now, we'll keep you posted. @albertospelta

**Comment by albertospelta** [comment] 2024-11-01 20:56
@iggyvic We were able to reproduce the error when trying to extract a VPAX from a model that includes objects requiring recalculation, such as calculated columns, hierarchies, and calculated tables. In these cases, because the object is not queryable and contains no data, the queries generated by the VertiPaq Analyzer library to extract data statistics may fail, resulting in an error like: 

> The expression referenced a relationship between 'Sales'[DateKey] and 'Date'[DateKey], which does not hold any data because it needs to be recalculated.

In these situations, when the model contains objects requiring recalculation, the error message displayed during the upload of the VPAX file to DAX Optimizer is the one you reported: _An error occurred while attempting to upload VPAX to DAX Optimizer: File contains corrupted data_. However, when using the _Collect Stats_ function, a detailed error message is displayed, as shown below.

![image](https://github.com/user-attachments/assets/172ee97b-06e6-4a06-b2ea-fa4a1310d1d2)

Could you please try extracting the VPAX using the _Collect Stats_ function and let us know if you see the recalculation error? Once the objects in your model are recalculated, this error should no longer occur, and the upload error should also be resolved. Could you confirm this ? Thanks.

/cc @otykier

**Comment by iggyvic** [comment] 2024-11-02 07:09
When pressing Collect Stats in the VertiPaq analyzer it processes without giving me a recalculation error. This was also what I did when exporting the vpax file to your web interface manually. 
<img width="267" alt="image" src="https://github.com/user-attachments/assets/4eb8af2f-d29d-4de9-bf2b-133757c5a930">
<img width="521" alt="image" src="https://github.com/user-attachments/assets/7634854f-91b7-48e4-bd47-c9f0e6225784">
If I try to use the integration to upload a new version of my model it tells me about the DQ table as before and then shows this
<img width="1058" alt="image" src="https://github.com/user-attachments/assets/230c0804-0023-4dd2-94c3-d973c208c189">
and in the online interface it looks like this
<img width="692" alt="image" src="https://github.com/user-attachments/assets/f25f31f7-c629-41e8-99a4-8991f81f53f7">
with Trace id: 7d8e875a-8c95-6a40-a37a-a28b087ab7cb (if I try to report it again)

**Comment by marcosqlbi** [comment] 2024-11-02 08:50
If you use DirectQuery, you should also enable "Read statistics from DirectQuery tables" in the VertiPaq Settings dialog box.
Clearly, we can do a better job in diagnostics - but in the meantime, I'd like to allow you to analyze your model!

**Comment by albertospelta** [comment] 2024-11-04 11:21
Thank you @iggyvic for the details you've provided. Just to confirm, after following these steps https://github.com/tabulartools/dax-optimizer/issues/34#issuecomment-2454402540, is the file valid, and are you able to analyze your model and view the results in TE3?

**Comment by iggyvic** [comment] 2024-11-04 12:12
Yes, if I follow the steps in your link and upload the exported vpax to the online service, the model is valid, and I can trigger the analyse from TE3.
<img width="1302" alt="image" src="https://github.com/user-attachments/assets/ab4e3086-74ca-4b7c-9b46-473e5532214b">
<img width="1296" alt="image" src="https://github.com/user-attachments/assets/06b29094-84ba-4078-ac6e-aebf0c60c576">
<img width="1299" alt="image" src="https://github.com/user-attachments/assets/7ec9ec95-7b31-432b-b462-8a1545b26ccb">

**Comment by albertospelta** [comment] 2024-11-11 17:13
@iggyvic We are closing this issue as the fix has been released in the latest version of TE3 ([3.18.1](https://docs.tabulareditor.com/te3/other/release-notes/3_18_1.html)). You should now be able to upload and analyze the VAPX file directly from TE3 without needing to go through the web application.
If you need any further assistance, feel free to comment here, and we can reopen the issue.

**Closed as completed by albertospelta** 2024-11-11 17:13 UTC
Labels: bug

**Comment by iggyvic** [comment] 2024-11-15 09:49
Thanks! I can confirm that uploading though TE3 indeed works. However, when I try to analyse it, I get the following error:
<img width="665" alt="image" src="https://github.com/user-attachments/assets/f1e342af-c148-4baf-8834-cbba49f232e7">
Analyse is successful if I initiate it on the TE3 uploaded version of the model though the web interface though:
<img width="698" alt="image" src="https://github.com/user-attachments/assets/d01e13c1-178e-466f-afb3-0d240ce4e52d">
Analysing in TE3 again, after I've already analysed online, works:
<img width="521" alt="image" src="https://github.com/user-attachments/assets/2ab31780-4ead-43b8-ac15-dca3ad60e042">
But if I upload a new version through TE3 and try agalysing it from TE3 it fails with the same error:
<img width="663" alt="image" src="https://github.com/user-attachments/assets/1b29c6ab-7444-4f09-b604-bbcb1d986efe">

**Comment by otykier** [comment] 2024-11-15 09:57
@iggyvic this is a known issue. You need to wait a minute or so after uploading, before you can initiate the analysis (this is typically the time it takes for the DAX Optimizer web service to validate the file after upload). Future versions of TE3 will show a better error message/prevent analysis execution until after the validation is complete.

**Comment by iggyvic** [comment] 2024-11-15 10:02
Ah, gotcha! I can confirm that this indeed was the case, thanks!
